# Generated by Django 6.0.3 on 2026-06-05 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('call_missed', 'Missed Audio Call'), ('call_accepted', 'Accepted Audio Call'), ('audio_comment', 'Voice Comment'), ('audio_like', 'Audio Post Like')], db_index=True, max_length=25)),
                ('message', models.TextField()),
                ('audio_file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_notifications_feed', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_audio_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_audio_feed_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='core_audio__recipie_05cf02_idx')],
            },
        ),
    ]
