# Generated by Django 6.0.3 on 2026-06-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiofeednotification'),
    ]

    operations = [
    ]
