# Generated by Django 6.0.3 on 2026-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_title_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
