# Generated by Django 6.0.3 on 2026-05-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_audio_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.CharField(default='https://res.cloudinary.com/your-cloud-name/image/upload/v1/cover.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://res.cloudinary.com/your-cloud-name/image/upload/v1/default.png', max_length=500),
        ),
    ]
