# Generated by Django 6.0.3 on 2026-05-08 13:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_cover_photo_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='auto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
