# Generated by Django 6.0.3 on 2026-05-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_radiosubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiochannel',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='radiochannel',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='radiochannel',
            name='spotify_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiochannel',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiochannel',
            name='channel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='radiochannel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radiochannel',
            name='topics',
            field=models.CharField(max_length=150),
        ),
    ]
