# Generated by Django 6.0.3 on 2026-05-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_radiochannel_frequency_radiochannel_owner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiochannel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='radiopost',
            name='listeners_count',
        ),
        migrations.AlterField(
            model_name='radiopost',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='radio_images/'),
        ),
        migrations.AlterField(
            model_name='radiopost',
            name='background_video',
            field=models.FileField(blank=True, null=True, upload_to='radio_videos/'),
        ),
        migrations.AlterField(
            model_name='radiopost',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.radiochannel'),
        ),
        migrations.AlterField(
            model_name='radiopost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='radiopost',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
