"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PYTHON_VERSION: 3.14
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hsy53_7qwm+25*bs898nbfk+s74owevbgl9_(!ts@7g#1y-r85'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# This allows your local computer AND Render to run the site
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rosetta',
   'django_recaptcha',


   'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
     
     'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware', # Keep this here
    
    # MOVE IT HERE!
    'django.middleware.locale.LocaleMiddleware',           
    
    'django.middleware.common.CommonMiddleware',           # It MUST be above this
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'plugbar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'core.context_processors.notification_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


import dj_database_url
import os

# Use Render's DATABASE_URL if it exists; otherwise, use your local Postgres
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', 'postgres://postgres:admin123@127.0.0.1:5432/mysite'),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


STATICFILES_DIRS = [BASE_DIR / 'static']
# added

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


from django.conf import settings
from django.conf.urls.static import static


USE_I18N = True

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('sw', 'Swahili'),
    ('fr', 'French'),
    ('es', 'Spanish'),
    ('pt', 'Portuguese'),
    ('ar', 'Arabic'),
    ('hi', 'Hindi'),
    ('zh-hans', 'Chinese (Simplified)'),
    ('ru', 'Russian'),
    ('ja', 'Japanese'),
    ('ko', 'Korean'),
]
   

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# settings.py

# Use the absolute path instead of the named 'login' 
# This bypasses i18n resolution issues during the initial redirect

# settings.py
# This forces Django to use your 'profile' name from urls.py
LOGIN_REDIRECT_URL = 'profile'
LOGOUT_REDIRECT_URL = 'login'

# This tells Django: "When a logged-out user tries to see notifications, 
# send them to my 'login' URL instead of the default '/accounts/login/'"

LOGIN_URL = 'login'


# Allow up to 10MB to stay in RAM (Faster than writing to Disk)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760


ROSETTA_MESSAGES_SOURCE_LANGUAGE_CODE = 'en'
ROSETTA_MESSAGES_SOURCE_LANGUAGE_NAME = 'English'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',


'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

]



RECAPTCHA_PUBLIC_KEY = ' 6LeiG7QsAAAAAKUF2Yj01yJ4X7CmhmDdXb4X_Z6X '
RECAPTCHA_PRIVATE_KEY = ' 6LeiG7QsAAAAAHvODEtyCrJ40ZUqkSMEoXevDStu  '

# This allows reCAPTCHA to work even if you are on localhost
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']



ACCOUNT_ADAPTER = 'core.adapters.MyAccountAdapter'




